### PR TITLE
Add draft of blogposts roadmap

### PR DESCRIPTION
**Pull request by SaveTheAles**
## Link it

#112 

Here is a plan for blogposts at 3rd block. 

UPD!!! Roadmap available [here](https://github.com/cybercongress/congress/blob/Blogposts_roadmap/blogposts/blogposts_roadmap.md)

### CODE REVIEW

**Comment by asadovka** [comment]
@SaveTheAles the link is broken(

**Comment by asadovka** [comment]
nice, not sure about 26 and 27 sprint, because perhaps we well have some king oh holidays.

Browser will be released every sprint so article "How far CYB release" (22 sprint) should be called "CYB. The next-gen web3 browser ". So the main goal is to describe web3 principles and present CYB in the new internet.

**Comment by hleb-albau** [comment]
@SaveTheAles from my side everything is cool.

**Comment by SaveTheAles** [comment]
@hleb-albau @arturalbov Let suspend this discussion for a short time till I reboot this doc in .md as @xhipster propose. After this we can talk about it.

**Comment by SaveTheAles** [comment]
@asadovka @hleb-albau @xhipster @arturalbov @Pechalka @litvintech @vstavetski 
I update roadmap in .md file
waiting for your review
available [here](https://github.com/cybercongress/congress/blob/Blogposts_roadmap/blogposts/blogposts_roadmap.md)

**Comment by asadovka** [comment]
@SaveTheAles nice!

**Comment by SaveTheAles** [comment]
@arturalbov the most important for us is regular articles. If you're ready to publish some extra articles it's OK. If you have ready-to-go articles and someone according to plan is not ready you also can post it.

**Comment by SaveTheAles** [comment]
@xhipster @Pechalka @vstavetski @litvintech 
Is it OK here? Can I merge it?

**Pull request merged**
