### PR TITLE
#320 cyberd add first economy draft

### PR DESCRIPTION
**Pull request by SaveTheAles**

### CODE REVIEW

**Comment by litvintech** [comment]
@SaveTheAles Please, add more details about bandwidth.

**Comment by SaveTheAles** [comment]
@litvintech @xhipster can we merge it?

**Comment by xhipster** [comment]
@SaveTheAles An article is great. But please, remove nested headings. Try to stick to a one level of headings in articles.

**Comment by SaveTheAles** [comment]
I've fixed according to @xhipster comments

**Comment by xhipster** [comment]
@litvintech your turn

**Pull request merged**
