### PR TITLE
euler-5 launch workshop

### PR DESCRIPTION
**Pull request by serejandmyself**
Create post for #303

### CODE REVIEW

**Comment by serejandmyself** [comment]
Bump =)

**Comment by xhipster** [comment]
@xhipster Please, approve. The post is readu

**Comment by serejandmyself** [comment]
> @xhipster Please, approve. The post is readu

@litvintech that is =)

**Comment by serejandmyself** [comment]
Long story short: 

The post has been reviewed and approved by everyone, hence merged

However, I am merging using admin right. Unfortunately 2 commits from @xhipster were not signed (do not have a verified sign next to them), hence master blocks merging without admin rights

**Pull request merged**
